core/urls.py
from django.urls import path
from core.views import index,category_list,category_product_list_view,vendor_list, vendor_product_list_view,product_detail_view,base,search,add_to_cart,cart_view,product_list
from django.conf import settings
from django.conf.urls.static import static
from core import views
app_name ="core"

urlpatterns = [
    path('', base, name='base'),
    path('vendors/', vendor_list, name='vendor_list'),
    path('vendors/<vid>', vendor_product_list_view, name='vendor_product_list_view'),
    path('category/', category_list, name='category_list'),
    path('category/<cid>', category_product_list_view, name='category_product_list_view'),
    path('products/<pid>', product_detail_view, name='product_detail_view'),
    path('index',index, name='index'),
    path('search',search, name='search'),
    path('add_to_cart/<pid>/', add_to_cart, name='add_to_cart'),
    path('cart_view/', cart_view, name='cart_view'),
     path('products/', product_list, name='product_list'),
     path('initiate-payment/', views.initiate_payment, name='initiate_payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/failure/', views.payment_failure, name='payment_failure'),
      path('update-cart-item/', views.update_cart_item, name='update_cart_item'),
    path('delete-cart-item/', views.delete_cart_item, name='delete_cart_item'),
    path('final_payment/', views.final_payment, name='final_payment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py


from django.contrib import admin
from django.urls import path , include
from core.views import index
from django.conf import settings
from django.conf.urls.static import static
from userauths.views import user_login
from core.views import base



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
     path('user/', include("userauths.urls")),
       path('userauths/loginform/', user_login, name='login_form'),
       path('core/base/', base, name='base'),
       
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# a59641e7-d0cd-43e9-87b4-d134dcc004f8

# c54724d1-1352-411e-b575-c1b4536553ee

# dc41ab9c-84c3-4a74-9142-92c8f5bde052

# 65df59f0-88dd-479f-8396-2f53ae4d7cbb

# cd476f27-53b6-4bff-8258-cf38f9c1e4a3

# ee5b8a8b-b3a5-44ed-860c-f83f55be6150

# 08e77816-238f-4dfd-a5e5-04d70989f8d6

# 7b2cd9c1-3239-42f7-b2cf-e9d2e538ee2d

userauths/urls.py
from django.urls import path
from userauths import views
app_name = "userauths"
urlpatterns = [
    path('sign-up/',views.register_view,name='sign-up'),
    path('loginform/',views.user_login,name='loginform'),
      path('logout/', views.user_logout, name='logout'),
]


core/models.py
from django.db import models
from userauths.models import User
from django.db import models
from django.utils.html import mark_safe


STATUS_CHOICE = (
    ("process","Processing"),
    ("shipped","Shipped"),
    ("delivered","Delivered")
)

STATUS = (
    ("draft","Draft"),
    ("disabled","Disabled"),
    ("rejected","Rejected"),
    ("in_review","In Review"),
    ("published","Published")
)
RATING = (
    (1,"✨"),
    (2,"✨✨"),
    (3,"✨✨✨"),
    (4,"✨✨✨✨"),
    (5,"✨✨✨✨✨")
)


def user_directory_path(instance,filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)
class Category(models.Model):
    cid = models.UUIDField(unique=True)
    title = models.CharField(max_length=100,default="Category")
    image = models.ImageField(upload_to="category/images",default="category.jpg")
    class Meta:
        verbose_name_plural = "Categories"
    def category_image(self):
        return mark_safe('< img src ="%s" width = "50" height = "50"/ >'% (self.image.url))
    def __str__(self) :
        return self.title
class Tags(models.Model):
    pass    
    
class Vendor(models.Model):
    vid = models.UUIDField(unique=True)
    title = models.CharField(max_length=100,default="weger")
    image = models.ImageField(upload_to='vendor/images',default="vendor.jpg")
    description = models.TextField(null=True,blank=True,default="this is vendor")
    address = models.CharField(max_length=100,default='kalanki')
    contact = models.CharField(max_length=100,default='123')
    chat_resp_time = models.CharField(max_length=100,default='123')
    shipping_on_time = models.CharField(max_length=100,default='123')
    authentic_rating = models.CharField(max_length=100,default='123')
    days_return = models.CharField(max_length=100,default='123')
    warranty_period = models.CharField(max_length=100,default='123')
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    
    class Meta:
        verbose_name_plural = "Vendors"
    def vendor_image(self):
        return mark_safe('< img src ="%s" width = "50" height = "50"/ >'% (self.image.url))
    def __str__(self) :
        return self.title
    
    
class Product(models.Model):
    pid = models.UUIDField(unique=True)
    title = models.CharField(max_length=100,default="products")
    image = models.ImageField(upload_to='product/images',default="product.jpg")
    description = models.TextField(null=True,blank=True,default="this is description")
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,null=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL,null=True)
    # tags = models.ForeignKey(Tags, on_delete=models.SET_NULL,null=True)
    price = models.DecimalField(max_digits=99999999,decimal_places=3,default="199")
    old_price = models.DecimalField(max_digits=99999999,decimal_places=3,default="299")
    specificaions = models.TextField(null=True,blank=True,default="this is specifications")
    product_status = models.CharField(choices=STATUS,max_length=10,default="in_review")
    
    status = models.BooleanField(default=True)
    in_Stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    digital = models.BooleanField(default=False)
    sku = models.UUIDField(unique=True)
    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(null=True,blank=True)


    class Meta:
            verbose_name_plural = "Products"
    def product_image(self):
            return mark_safe('< img src ="%s" width = "50" height = "50"/ >'% (self.image.url))
    def __str__(self) :
            return self.title
    def get_percentage(self):
        new_price = (self.price/self.old_price)*100
        return new_price
    
    
    
    
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product_images/images",default="product.jpg")
    product = models.ForeignKey(Product,related_name='p_image', on_delete=models.SET_NULL,null=True)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
            verbose_name_plural = "Product Images"
    
    
    
    

class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=99999999,decimal_places=3,default="199")
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices=STATUS,max_length=300000000,default="processing")
    
    class Meta:
          verbose_name_plural = "Cart Order"
          
    
    
class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    product =  models.ForeignKey(Product, on_delete=models.SET_NULL,null=True)
    invoice_no = models.CharField(max_length=200)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=99999999,decimal_places=3,default="199")
    total = models.DecimalField(max_digits=99999999,decimal_places=3,default="199")
    
    class Meta:
          verbose_name_plural = "Cart Order Items"
          
    def order_img(self):
         return mark_safe('< img src ="/media/%s" width = "50" height = "50"/ >'% (self.image))
     
     
     
     
class ProductReview(models.Model):
   
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "Product Reviews"
          
    def __str__(self) :
        return self.product.title   
    def get_rating(self) :
        return self.rating
    
    
class WishList(models.Model):
   
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "Wishlists"
          
    def __str__(self) :
        return self.product.title   
    
    
    
class Address(models.Model):
    
  user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
  address = models.CharField(max_length=100,null=True)
  status = models.BooleanField(default=True)
  class Meta:
        verbose_name_plural = "Addresses"

core/views.py
from django.shortcuts import render, HttpResponse
from core.models import CartOrder,Category,Vendor,Product,ProductImages,ProductReview,CartOrderItems,WishList,Address
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.conf import settings
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import render
from django.conf import settings
import uuid
import hmac
import hashlib
from django.views.decorators.csrf import csrf_exempt
from .models import CartOrder, CartOrderItems
from .forms import UpdateQuantityForm, DeleteItemForm
import base64

from django.views.decorators.http import require_POST

def base(request):
    products = Product.objects.all().order_by("-id")
    categories = Category.objects.all()
    
    # products = Product.objects.filter(featured = True).order_by("-id")
    context = {
        "products":products,
         "categories":categories
    }
    return render(request,'core/base.html',context)

def index(request):
    products = Product.objects.all().order_by("-id")
    # products = Product.objects.filter(featured = True).order_by("-id")
    context = {
        "products":products
    }
    return render(request,'core/index.html',context)

def category_list(request):
    categories = Category.objects.all()
    context = {
        "categories":categories
    }
    return render(request,'core/category_list.html',context)

def category_product_list_view(request,cid):
    category = Category.objects.get(cid=cid)
    # products = Product.objects.filter(product_status ="published",category = category)
    products = Product.objects.filter(category = category)
    context = {
        "category":category,
        "products":products
    }
    return render(request,'core/category_product_list_view.html',context)

def vendor_list(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors":vendors
    }
    return render(request,'core/vendor_list.html',context)
def vendor_product_list_view(request,vid):
    vendor = Vendor.objects.get(vid=vid)
    # products = Product.objects.filter(product_status ="published",category = category)
    products = Product.objects.filter(vendor = vendor)
    context = {
        "vendors":vendor,
         "products":products
    }
    return render(request,'core/vendor_product_list_view.html',context)

def product_detail_view(request,pid):
    product = Product.objects.get(pid=pid)
    p_image = product.p_image.all()
    r_product = Product.objects.filter(category = product.category).exclude(pid=pid)
    context = {
        
         "product":product,
         "p_image":p_image,
         "r_product":r_product
    }
    return render(request,'core/product_detail_view.html',context)

def search(request):
    query = request.GET.get("query")
    products = Product.objects.filter(title__icontains=query).order_by("-date")
    context = {
        "products":products,
        "query":query
    }
    return render(request,'core/search.html',context)
@login_required
def add_to_cart(request, pid):
    product = get_object_or_404(Product, pid=pid)
    
    # Get or create a cart for the user
    cart, created = CartOrder.objects.get_or_create(user=request.user)
    
    # Check if the product is already in the cart
    cart_item = CartOrderItems.objects.filter(order=cart, product=product).first()
    
    # If the item is already in the cart, update quantity
    if cart_item:
        cart_item.qty += 1
        cart_item.save()
    else:
        # If the item is not in the cart, create a new cart item
        cart_item = CartOrderItems.objects.create(order=cart, product=product, qty=1)
    
    return redirect('core:cart_view')   
@login_required
def cart_view(request):
    cart = CartOrder.objects.filter(user=request.user).first()
    total_price = 0

    if cart:
        for item in cart.cartorderitems_set.all():
            total_price += item.product.price * item.qty

    context = {'cart': cart, 'total_price': total_price}
    return render(request, 'core/cart.html', context)
@login_required
@require_POST
def update_cart_item(request):
    item_id = request.POST.get('item_id')
    action = request.POST.get('action')
    item = get_object_or_404(CartOrderItems, id=item_id, order__user=request.user)

    if action == 'increase':
        item.qty += 1
    elif action == 'decrease' and item.qty > 1:
        item.qty -= 1
    item.save()

    return JsonResponse({'qty': item.qty})
def final_payment(request):
    cart = CartOrder.objects.filter(user=request.user).first()
    total_price = 0
    delivery_charge = 100
    

    if cart:
        for item in cart.cartorderitems_set.all():
            total_price += item.product.price * item.qty
    tax = 0
    final_price = total_price + delivery_charge + tax
    context = {'cart': cart, 'total_price': total_price,"delivery_charge":delivery_charge,"final_price":final_price,'tax':tax}
    return render(request, 'core/cart.html', context)

@login_required
@require_POST
def delete_cart_item(request):
    item_id = request.POST.get('item_id')
    item = get_object_or_404(CartOrderItems, id=item_id, order__user=request.user)
    item.delete()
    return JsonResponse({'success': True})
def product_list(request):
    vendor_ids = request.GET.get('vendors', '').split(',')
    category_ids = request.GET.get('categories', '').split(',')

    products = Product.objects.all()

    if vendor_ids != ['']:
        products = products.filter(vendor__vid__in=vendor_ids)
    
    if category_ids != ['']:
        products = products.filter(category__cid__in=category_ids)

    if request.headers.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        html = render_to_string('product_list_partial.html', {'products': products})
        return JsonResponse({'html': html})

    context = {
        'products': products,
        'vendors': Vendor.objects.all(),
        'categories': Category.objects.all(),
    }
    return render(request, 'core/product_list_partial.html', context)



# payment


def generate_signature(total_amount, transaction_uuid, product_code, secret_key):
    concatenated_data = f'total_amount={total_amount}&transaction_uuid={transaction_uuid}&product_code={product_code}'
    signature = hmac.new(secret_key.encode('utf-8'), concatenated_data.encode('utf-8'), hashlib.sha256).digest()
    base64_signature = base64.b64encode(signature).decode('utf-8')
    return base64_signature

def initiate_payment(request):
    # Generate unique transaction ID
    transaction_id = uuid.uuid4()

    # Prepare payment data
    payment_data = {
        'amount': 200,
        'tax_amount': 10,
        'total_amount': 110,
        'transaction_uuid': transaction_id,
        'product_code': 'EPAYTEST',
        'product_service_charge': 0,
        'product_delivery_charge': 0,
        'success_url': request.build_absolute_uri('/payment/success/'),
        'failure_url': request.build_absolute_uri('/payment/failure/'),
        'signed_field_names': 'total_amount,transaction_uuid,product_code',
    }

    # Generate signature
    secret_key = "8gBm/:&EnhH.1/q"
    
    signature = generate_signature(payment_data['total_amount'], payment_data['transaction_uuid'], payment_data['product_code'], secret_key)

    context = {
        'payment_data': payment_data,
        'signature': signature,
        'esewa_payment_url': 'https://rc-epay.esewa.com.np/api/epay/main/v2/form',
    }

    return render(request, 'core/initiate_payment.html', context)


@csrf_exempt
def payment_success(request):
    # Handle successful payment here
    return render(request, 'payment/success.html')


@csrf_exempt
def payment_failure(request):
    # Handle failed payment here
    return render(request, 'payment/failure.html')

templates/core/base.html

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script src='https://cdn.tailwindcss.com'></script> 
{% load static %}
<title> {% block title %}  welcome {% endblock  %}  |   HTML Heading Template</title>
</head>
<body>
    
 
    <nav class="bg-blue-900 text-white p-8">
      <div class="container mx-auto flex justify-between items-center">
        <a href="#" class="text-2xl font-bold">Ecommerce Store</a>
        <ul class="flex space-x-4">
          <li><a href="{% url 'core:base' %}" class="hover:underline">
            Home</a></li>
          
          <li><a href="#" class="hover:underline">About</a></li>
          <li><a href="#" class="hover:underline">Contact</a></li>
          <a href="{% url 'core:category_list' %}" class="ml-4 flex items-center">
           
            <span>Categories</span>
          </a>
         
        </ul>
        <div class="flex items-center">
        
          <form id="searchForm" action="{% url 'core:search' %}" method="GET">
            <input id="searchInput" type="text" name="query" placeholder="Search..." class="text-blue-900 border border-gray-400 rounded-l px-2 py-1 focus:outline-none focus:border-blue-500">
            <button type="submit" class="bg-orange-500 text-white px-4 py-1 rounded-r hover:bg-orange-600 focus:outline-none">Search</button>
        </form>
        
        
        {% if request.user.is_authenticated%}
        <a href="{% url 'core:index' %}" class="hover:text-2xl ml-4 flex items-center">
          <i class="fas fa-shopping-bag mr-1"></i>
          Shop
        </a>
        
        <a href="{% url 'core:cart_view' %}" class="hover:text-2xl ml-4 flex items-center">
        
          Cart
        </a>
        
        <a href="{% url 'userauths:logout' %}" class="hover:text-2xl ml-4 flex items-center">
          Logout
          
         
        </a>
        
        {% else %}
          <a href="{% url 'userauths:loginform' %}" class="ml-4 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H4m16-4H4m16 8H4m4 4h16m-8-8a4 4 0 11-8 0 4 4 0 018 0z" />
            </svg>
            <span>Login</span>
          </a>
          <a href="{% url 'userauths:sign-up' %}" class="ml-4 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
            </svg>
            <span>Signup</span>
          </a>
          {% endif %}

        </div>
      </div>
    </nav>
    <div class=" mx-auto">

      <div id="default-carousel" class="relative" data-carousel="static">
            
            <div class="overflow-hidden relative h-56 rounded-lg sm:h-64 xl:h-80 2xl:h-96">
                
                <div class="hidden duration-700 ease-in-out flex justify-center" data-carousel-item>
                    <img src="{% static 'images/hero1.jpg' %}" class="max-w-full h-auto " alt="...">
                </div>
               
                <div class="hidden duration-700 ease-in-out flex justify-center" data-carousel-item>
                    <img src="{% static 'images/hero2.png' %}" class="max-w-full h-auto " alt="...">
                </div>
              
                <div class="hidden duration-700 ease-in-out flex justify-center" data-carousel-item>
                    <img src="{% static 'images/hero3.png' %}" class="max-w-full h-auto " alt="...">
                </div>
            </div>
            <!-- Slider indicators -->
            <div class="flex absolute bottom-5 left-1/2 z-30 space-x-3 -translate-x-1/2">
                <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 1" data-carousel-slide-to="0"></button>
                <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 2" data-carousel-slide-to="1"></button>
                <button type="button" class="w-3 h-3 rounded-full" aria-current="false" aria-label="Slide 3" data-carousel-slide-to="2"></button>
            </div>
            <!-- Slider controls -->
            <button type="button" class="flex absolute top-0 left-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none" data-carousel-prev>
                <span class="inline-flex justify-center items-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-blue-900/30 bg-orange-500 group-hover:bg-orange-600 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                    <svg class="w-5 h-5 text-white sm:w-6 sm:h-6 dark:text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
                    <span class="hidden">Previous</span>
                </span>
            </button>
            <button type="button" class="flex absolute top-0 right-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none" data-carousel-next>
                <span class="inline-flex justify-center items-center w-8 h-8 rounded-full sm:w-10 sm:h-10  bg-orange-500 group-hover:bg-orange-600 dark:group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white dark:group-focus:ring-gray-800/70 group-focus:outline-none">
                    <svg class="w-5 h-5 text-white sm:w-6 sm:h-6 dark:text-gray-800" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
                    <span class="hidden">Next</span>
                </span>
            </button>
        </div>
    
    
        <script src="https://unpkg.com/flowbite@1.4.0/dist/flowbite.js"></script>
    </div>
    {% block content %}
    <div class="flex justify-center mt-4">
      <button id="filter-button" class="bg-orange-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
          Filters
      </button>
  </div>
  
  <div class="mt-4 flex justify-center" id="filter-section" style="display: none;">
      <div class="w-100 justify-center  mx-auto flex">
          <div class="mr-2 bg-blue-200 rounded-lg p-4">
              <label class="block text-orange-700 text-lg font-bold mb-2">Vendor:</label>
              {% for vendor in vendors %}
                  <div class="flex items-center mb-2">
                      <input type="checkbox" name="vendor" value="{{ vendor.vid }}" class="vendor-checkbox text-blue-500" id="vendor-{{ vendor.vid }}">
                      <label for="vendor-{{ vendor.vid }}" class="ml-2 text-lg text-gray-700 font-medium font-serif">{{ vendor.title }}</label>
                  </div>
              {% endfor %}
          </div>
  
          <div class="bg-orange-200 w-64 rounded-lg p-4 ">
              <label class="block text-orange-700 text-lg font-bold mb-2">Category:</label>
              {% for category in categories %}
                  <div class="flex items-center mb-2">
                      <input type="checkbox" name="category" value="{{ category.cid }}" class="category-checkbox text-orange-500" id="category-{{ category.cid }}">
                      <label for="category-{{ category.cid }}" class="ml-2 text-lg text-gray-700 font-medium font-serif">{{ category.title }}</label>
                  </div>
              {% endfor %}
          </div>
      </div>
  </div>
  
  <script>
      document.getElementById("filter-button").addEventListener("click", function() {
          var filterSection = document.getElementById("filter-section");
          filterSection.style.display = (filterSection.style.display === "none" || filterSection.style.display === "") ? "block" : "none";
      });
  </script>
  
<div id="product-list">
    {% include 'core/product_list_partial.html' %}
</div>

<script>
    $(document).ready(function() {
        $('.vendor-checkbox, .category-checkbox').change(function() {
            updateProductList();
        });
    });

    function updateProductList() {
        let selectedVendors = [];
        $('.vendor-checkbox:checked').each(function() {
            selectedVendors.push($(this).val());
        });

        let selectedCategories = [];
        $('.category-checkbox:checked').each(function() {
            selectedCategories.push($(this).val());
        });
        console.log("Selected Vendors: ", selectedVendors);
        console.log("Selected Categories: ", selectedCategories);
        $.ajax({
            url: "{% url 'core:product_list' %}",
            data: {
                vendors: selectedVendors.join(','),
                categories: selectedCategories.join(',')
            },
            success: function(data) {
                $('#product-list').html(data);
            }
        });
    }
</script>


{% endblock content %}


      
      <footer class="bg-blue-900 mt-5 w-full">
        <div class="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
          <div class="flex justify-between items-center text-gray-300">
            <span>&copy; 2024 Your Website. All rights reserved.</span>
            <div class="flex space-x-4">
              <a href="#" class="hover:text-white">Privacy Policy</a>
              <a href="#" class="hover:text-white">Terms of Service</a>
            </div>
          </div>
        </div>
      </footer>
      
  
</body>
</html>

templates/core/product_list_partial.html
<div class="container flex flex-row m-5">
    <div class="w-1/5">
      <h2 class="text-2xl font-bold mb-8 ">Categories</h2>
      <div class="grid gap-4">
        {% for category in categories %}
        <a href="{% url 'core:category_product_list_view' category.cid %}" class="block bg-white rounded-lg shadow-md overflow-hidden hover:bg-gray-100 transition duration-300">
          <div class="p-4">
            <h3 class="text-xl font-semibold mb-2">{{ category.title }}</h3>
            
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
  
    
    <div class="ml-20 w-full px-6 ">
      <div class=" rounded-lg shadow-lg overflow-hidden">
      <h2 class="text-2xl font-bold text-orange-600 mb-8 text-center ">Popular Products</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        {% for product in products %}
        <!-- Product Card -->
        <a href="{% url 'core:product_detail_view' product.pid %}">
        <div class="bg-white rounded-lg shadow-md overflow-hidden">
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="w-full h-64 object-cover">
            <div class="p-4">
                <h3 class="text-xl font-semibold mb-2">{{ product.title }}</h3>
                {% comment %} <h3 class="text-2xl font-bold mb-2">{{ product.category.title }}</h3>
                <h3 class="text-2xl font-bold mb-2">{{ product.vendor.title }}</h3>
                <p class="text-gray-600">{{ product.description }}</p> {% endcomment %}
                <p class="text-red-600">-{{ product.get_percentage |floatformat:0 }}</p>
                <div class="mt-4 flex justify-between items-center">
                    <span class="font-bold">${{ product.price }}</span>
                    <del class="font-bold">${{ product.old_price }}</del>
  
                </div>
            </div>
        </div>
       </a>
        {% endfor %}
    </div>
    </div>
  </div>
  </div>
  